import { getServerSession } from "next-auth";
import { authOptions } from "../../pages/api/auth/[...nextauth]";
import Login from "./components/Login";
import SessionProvider from "./components/SessionProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" className="bg-slate-700">
      <body>
        <SessionProvider session={session}>
          {!session ? <Login /> : <div className="">{children}</div>}
        </SessionProvider>
      </body>
    </html>
  );
}
